ehealth/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/fhsa/'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^fhsa/', include('fhsa.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fhsa/urls.py
from django.conf.urls import patterns, url
from . import views
from django.contrib.auth.views import login

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$',login, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^about/$', views.about, name="about"),
    url(r'^user_page/$', views.user_page, name="user_page"),
    url(r'^search/medline/$', views.medline, name="medline"),
    url(r'^search/$', views.search, name="search"),
    url(r'^folder/(?P<folder_name_slug>[\w\-]+)/$', views.folder, name='category'),
    url(r'^save/$', views.save, name='save'),
    url(r'^create_folder/$', views.create_folder, name="create_folder"),
    ]

fhsa/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

# Create your models here.
class UserProfile(models.Model):
    """
    The profile for users of the site
    """
    user = models.OneToOneField(User, null=True)
    avatar = models.ImageField(upload_to='profile_images', blank=True)
    DOB = models.DateField()
    email = models.EmailField(blank=True)
   # age = int((date.today() - DOB).days / 365.2425)
    MALE = 'M'
    FEMALE = 'F'
    GENDERS = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDERS)

    def __unicode__(self):
        return self.user.username

class UserFolder(models.Model):
    """
    Folders that users can create
    """
    name = models.CharField(max_length=32, unique=True)
    description = models.TextField(max_length=250, null=True)
    user = models.ForeignKey(UserProfile, null=True)
    id = models.AutoField(primary_key=True)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(UserFolder, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

class Result(models.Model):
    """
    Results from APIs
    """
    title = models.CharField(max_length=128, null=True)
    description = models.CharField(max_length=128, null=True)
    url = models.URLField(primary_key = True)
    source = models.CharField(max_length=50, null=True)
    sentimentality = models.IntegerField(default=0)
    readability = models.IntegerField(default=0)
    sensitivity = models.IntegerField(default=0)
    retrieved = models.DateField(null=True)

    def __unicode__(self):
        return self.title

fhsa/forms.py
from django import forms
from django.contrib.auth.models import User
from fhsa.models import UserProfile, UserFolder

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar', 'gender', 'DOB',)

class UserFolderForm(forms.ModelForm):
    class Meta:
        model = UserFolder
        fields = ('name', 'description', 'user')

fhsa/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from fhsa.forms import UserForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from identiji import generateAvatar
from .models import UserFolder, UserProfile, User
from cacheSearch import doSearch
import os
from datetime import date

def getRequestParam(p,request):
    if p in request.GET:
        return request.GET[p]
    if p in request.POST:
        return request.POST[p]
    return ""

@login_required
def home(request):
  return HttpResponse('/fhsa/')

def user_page(request):
    user = UserProfile.objects.get(user=request.user)
    folders = UserFolder.objects.filter(user = user)
    userorg = User.objects.get(username = request.user)
    avatarSrc = "/fhsastatic/profile_images/" + str(user) + ".png"
    return render(request, 'fhsa/user_page.html', {'user': user, 'folders': folders, 'userorg': userorg, 'avatarSrc': avatarSrc})

def index(request):
    if request.method == 'POST':
        form = IndexForm(request.POST)
        if form.is_valid():
            return search(request)

    if request.user.is_anonymous():
        return render(request, 'fhsa/index.html', {})
    else:
        user = UserProfile.objects.get(user=request.user)
        avatarSrc = "/fhsastatic/profile_images/" + str(user) + ".png"
        return render(request, 'fhsa/index.html', {"avatarSrc":avatarSrc})

def search(request):
    def formatURL(s):
        if s[0:8] == "https://":
            return s
        elif s[0:7] == "http://":
            return s
        return "http://" + s

    logged = True
    global query
    global result_list
    try:
        user = UserProfile.objects.get(user=request.user)
    except:
        user = None
    query = getRequestParam("query", request)
    api = getRequestParam("api", request)

    if api not in [ "medline", "bing", "healthfinder" ]:
        api = "*"


    result_list = doSearch(query, api=api, user=user)
    avatarSrc = "/fhsastatic/profile_images/" + str(user) + ".png"
    return render(request, 'fhsa/search.html', {'result_list': result_list, "searchterm":query, 'avatarSrc':avatarSrc} )

@login_required
def save(request):
    user = UserProfile.objects.get(user=request.user)
    folders = UserFolder.objects.filter(user = user)
    userorg = User.objects.get(username = request.user)
    return render(request, 'fhsa/save.html', {'user': user, 'userorg': userorg, 'folders': folders, 'result_list': result_list})

@login_required
def create_folder(request):
    return render(request, 'fhsa/create_folder.html', {})

def folder(request, folder_name_slug):
    context_dict = {}
    try:
        folder = UserFolder.objects.get(slug=folder_name_slug)
        context_dict['folder'] = folder
        user = folder.user

    except UserFolder.DoesNotExist:
        pass

    avatarSrc = "/fhsastatic/profile_images/" + str(user) + ".png"
    context_dict['avatarSrc'] = avatarSrc

    return render(request, 'fhsa/folder.html', context_dict)

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/fhsa/')

def about(request):
    if request.user.is_anonymous():
        return render(request, 'fhsa/about.html', {})
    else:
        user = UserProfile.objects.get(user=request.user)
        avatarSrc = "/fhsastatic/profile_images/" + str(user) + ".png"
        return render(request, 'fhsa/about.html', {"avatarSrc":avatarSrc})

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if not os.path.exists("fhsastatic/profile_images"):
                os.mkdir("fhsastatic/profile_images")

            if 'avatar' in request.FILES:
                profile.avatar = request.FILES['avatar']
            else:
                profile.avatar = generateAvatar(str(profile.user), "fhsastatic/profile_images")

            profile.save()

            registered = True

        else:
            print user_form.errors, profile_form.errors

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,
            'fhsa/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered} )

def medline(request):
    title = getRequestParam("r", request).encode('ascii', 'ignore')
    query = getRequestParam("q", request).encode('ascii', 'ignore')

    def findResult(title, results):
        for result in results:
            if result["title"].encode('ascii', 'ignore') == title:
                return result

    return render(request,
        'fhsa/medline.html',
        {"r":findResult(title, doSearch(query))})

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">

  <head>
    <meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/index.css' %}">
	<Title>{% block title %}{% endblock%}</Title>
  </head>

  <body>
	<ul id="nav-bar">
		<li class="home"><a class="header-link" href="/fhsa/">eHealth</a> 
		{% if user.is_authenticated %}
			<li class="header-element"><a class="header-link" href="/fhsa/logout">Logout</a></li>
			<li class="header-element"><a id="profile-link" href="/fhsa/user_page">
				<img id="profile-pic" src="{{ avatarSrc }}" alt="profile picture" width=30 height=30/>
				{{ user.username }}
			</a></li>
		{% else %}
			<li class="header-element"><a class="header-link" href="/fhsa/register/">Register Here</a></li>
			<li class="header-element"><a class="header-link" href="/fhsa/login/">Login</a></li>
		{% endif %}
	</ul>
	
	<div class="container">
	{% block body %}
	{% endblock %}
	</div>
	
  </body>
</html>

templates/fhsa/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}About{% endblock %}

{% block body %}
	<div id="about-div">
		<h1 class="page-title">About</h1>
		<p id="about-text">
			A web application to make searching for possible illnesses, remedies, and articles relating to
			medical concerns simple.
		</p>
		<div>
			<h1 class="page-title">Features</h2>
			<ul id="features-list">
				<li>
					The ability to create a unique profile along with an auto-generated 'identijii' from your username.
				</li>
				<li>
					Search three different APIs, with the ability to personalise results on what APIs to look at.
				</li>
				<li>
					Results from each API are ranked on the sensitivity of the article - a calculation of the readability and sentimentality.
				</li>
			</ul>
		</div>
	</div>
{% endblock %}

templates/fhsa/create_folder.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Create Folder{% endblock %}

{% block body %}
	Started
{% endblock %}

templates/fhsa/folder.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ folder.name }}{% endblock %}

{% block body %}
	<h1 class="page-title">{{ folder.name }} by {{ folder.user }}</h1>
    <div id="folder-div">
        <p>{{ folder.description }}</p>
		<ul id="folder-links">
			<li class="folder-link">test1</li>
			<li class="folder-link">test2</li>
		</ul>
    </div>
{% endblock %}

templates/fhsa/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}eHealth{% endblock %}

{% block body %}
	<div id="search-div">
		{% if user.is_authenticated %}
			<h1>Welcome back, {{  user.username }} </h1>
		{% else %}
			<h1>Welcome to eHealth</h1>
		{% endif %}
		<form id="search" id="user_form" method="post" action="{% url 'search' %}">
			{% csrf_token %}
			<!-- Display the search form elements here -->
			<input id="search-bar" type="text" size="50" name="query" value="" id="query" placeholder="Type symptoms here" />
			<input id="search-button" type="submit" name="submit" value="Search" />
		</form>
	</div>
		
	<div id="footer">
		<a href="/fhsa/about/">About</a>
	</div>
	
{% endblock %}
	

templates/fhsa/login.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{% endblock %}

{% block body %}
    <h1>Login</h1>

        <form id="login_form" method="post" action="/login/">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" />
        </form>
{% endblock %}

templates/fhsa/medline.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{r.title}}</title>
</head>
<body>
    <h1><a href="/fhsa/">eHealth</a></h1>
    <h2>{{r.title}}</h2>
    <p>
    {{r.description}}
    </p>
    <p>Sourced from {{r.source}}</p>
</body>
</html>

templates/fhsa/register.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Register{% endblock %}

{% block body %}
	{% if registered %}
		<h1 id="centered-header">Thank you for registering!</h1>
	{% else %}
    <h1 class="page-title">Register with eHealth</h1>
	<div id="register">
		<form id="register-form" id="user_form" method="post" action="/fhsa/register/"
                enctype="multipart/form-data">

			{% csrf_token %}
			<input class="input-text" id="id_username" maxlength="30" name="username" type="text" placeholder="Username">
			<span class="helptext"> Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.</span><br/>
			<input class="input-text" id="id_email" maxlength="254" name="email" type="email" placeholder="Email address"><br/>
			<input class="input-text" id="id_password" name="password" type="password" placeholder="Password"><br/>
			<label for="id_avatar"> Avatar:</label>
			<input id="avatar-select" id="id_avatar" name="avatar" type="file"><br/>
			<select class="input-select" id="id_gender" name="gender">
				<option value="" selected="selected">Gender</option>
				<option value="M">Male</option>
				<option value="F">Female</option>
			</select><br/>
			<input class="input-text" id="id_DOB" name="DOB" type="text" placeholder="Date of Birth"><br/>
			<input id="register-button" type="submit" name="submit" value="Register" />
			</form>
		{% endif %}
	</div>
{% endblock %}

templates/fhsa/save.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Save Result{% endblock %}

{% block body %}
		<h1 class="page-title">Save Result</h1>
		<div class="centered-div">Where would you like to save this result?</div>
		<div id="save-folders-container">
			<div id="save-folders">
				{% csrf_token %}
				{% for f in folders %}
					<div class="folder">
						<a class="folder-title" href="/fhsa/folder/{{ f.slug }}">{{ f.name }}</a></br>
						<p class="folder-description">
							{{ f.description }}
						</p>
					</div>
				{% endfor %}
			</div>
			<ul id="save-folder-options">
				<li class="folder-list-option"><a class="folder-option" href="/fhsa/create_folder/">Add a New Folder</a>
			</ul>
		</div>
{% endblock %}

templates/fhsa/search.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Search{% endblock %}

{% block body %}
	<div id="search-results">
		<form id="search2" id="user_form" method="post" action="{% url 'search' %}">
            {% csrf_token %}
            <input id="search-bar" type="text" size="50" name="query" value="" id="query" placeholder="Type symptoms here" />
            <input id="search-button" type="submit" name="submit" value="Search" />
            </form>
			<a class="mode" href="?query={{searchterm}}&api=*">All</a>  <a class="mode" href="?query={{searchterm}}&api=bing">Bing</a>  <a class="mode" href="?query={{searchterm}}&api=medline">Medline</a>  <a class="mode" href="?query={{searchterm}}&api=healthfinder">HealthFinder</a>
	</div>
	<div id="results">
		<h1>Results</h1>
		{% if result_list %}
			<div>
				{% for result in result_list %}
					<div>
						<h4><a class="result-header" href="{{ result.url }}">{{ result.title }}</a></h4>
						<p>{{ result.shortDescription }}</p>
						<p><a id="save" href="/fhsa/save">Save</a> Sensitivity: {{result.sensitivity}}</p>
					</div>
				{% endfor %}
			</div>			
		{% endif %}			
	</div>
{% endblock %}

templates/fhsa/user_page.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ user.user }}'s Page{% endblock %}

{% block body %}
	<div id="user-header">
		<h1>{{user.user}}'s</h1>
	</div>
	
	<div id="bio">
		<h1>Bio</h1>
		<img id="profile-image" src="{{ avatarSrc }}" height=250 width=250>
		<p id="bio-info">
			Date of Birth: {{ user.DOB }} <br/>
			Gender: {{ user.gender }}<br/>
			Email: {{ userorg.email }}<br/>
		</p>
	</div>
	
	<div id="folder-container">
		<div id="folders">
			{% csrf_token %}
			{% for f in folders %}
				<div class="folder">
					<a class="folder-title" href="/fhsa/folder/{{ f.slug }}">{{ f.name }}</a></br>
					<p class="folder-description">
						{{ f.description }}
					</p>
				</div>
			{% endfor %}
		</div>
		<ul id="folder-options">
			<li class="folder-list-option"><a class="folder-option" href="/fhsa/create_folder/">Add a New Folder</a>
		</ul>
	</div>
			
{% endblock %}